<a href="https://colab.research.google.com/github/EduardaSantosDiniz/Praticando_Python/blob/main/PraticandoPythoni.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_excel('/content/base_vendas_supermercado.xlsx')
df

,ID_Venda,Filial,Cidade,Genero,Produto,Preco_Unitario,Quantidade,Forma_Pagamento,Data,Hora,Avaliacao
0,1,C,Belo Horizonte,Feminino,Carne,73.63,5,Dinheiro,2024-01-03,13:15,2
1,2,A,São Paulo,Masculino,Arroz,93.96,7,Cartão,2024-03-25,16:35,7
2,3,C,São Paulo,Masculino,Pão,19.76,9,Pix,2024-10-08,19:15,3
3,4,C,São Paulo,Feminino,Arroz,8.52,3,Pix,2024-11-23,19:13,3
4,5,A,São Paulo,Masculino,Açúcar,74.63,8,Cartão,2024-10-30,13:21,5
...,...,...,...,...,...,...,...,...,...,...,...
295,296,B,São Paulo,Masculino,Carne,71.15,1,Dinheiro,2024-11-29,12:09,2
296,297,B,Belo Horizonte,Masculino,Carne,92.67,8,Dinheiro,2024-01-20,21:48,3
297,298,B,São Paulo,Masculino,Feijão,19.70,3,Dinheiro,2024-05-25,17:04,3
298,299,B,Belo Horizonte,Masculino,Pão,57.66,6,Dinheiro,2024-11-11,22:42,1
299,300,B,São Paulo,Feminino,Leite,91.72,9,Cartão,2024-06-08,11:46,3

In [3]:
#criando a coluna com o faturamento
df["Faturamento"] = df['Preco_Unitario'] * df['Quantidade']
df

,ID_Venda,Filial,Cidade,Genero,Produto,Preco_Unitario,Quantidade,Forma_Pagamento,Data,Hora,Avaliacao,Faturamento
0,1,C,Belo Horizonte,Feminino,Carne,73.63,5,Dinheiro,2024-01-03,13:15,2,368.15
1,2,A,São Paulo,Masculino,Arroz,93.96,7,Cartão,2024-03-25,16:35,7,657.72
2,3,C,São Paulo,Masculino,Pão,19.76,9,Pix,2024-10-08,19:15,3,177.84
3,4,C,São Paulo,Feminino,Arroz,8.52,3,Pix,2024-11-23,19:13,3,25.56
4,5,A,São Paulo,Masculino,Açúcar,74.63,8,Cartão,2024-10-30,13:21,5,597.04
...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,B,São Paulo,Masculino,Carne,71.15,1,Dinheiro,2024-11-29,12:09,2,71.15
296,297,B,Belo Horizonte,Masculino,Carne,92.67,8,Dinheiro,2024-01-20,21:48,3,741.36
297,298,B,São Paulo,Masculino,Feijão,19.70,3,Dinheiro,2024-05-25,17:04,3,59.10
298,299,B,Belo Horizonte,Masculino,Pão,57.66,6,Dinheiro,2024-11-11,22:42,1,345.96
299,300,B,São Paulo,Feminino,Leite,91.72,9,Cartão,2024-06-08,11:46,3,825.48

In [4]:
#top 3 produtos com o faturamento mais alto
top = df.groupby(['Produto'])['Faturamento'].sum().sort_values(ascending=False)
top.head(3)

Produto
Café     12559.89
Carne    10360.30
Pão      10043.83
Name: Faturamento, dtype: float64

In [5]:
#criando a coluna com os dias da semana
df['DiaSemana'] = df['Data'].dt.day_name()
df

,ID_Venda,Filial,Cidade,Genero,Produto,Preco_Unitario,Quantidade,Forma_Pagamento,Data,Hora,Avaliacao,Faturamento,DiaSemana
0,1,C,Belo Horizonte,Feminino,Carne,73.63,5,Dinheiro,2024-01-03,13:15,2,368.15,Wednesday
1,2,A,São Paulo,Masculino,Arroz,93.96,7,Cartão,2024-03-25,16:35,7,657.72,Monday
2,3,C,São Paulo,Masculino,Pão,19.76,9,Pix,2024-10-08,19:15,3,177.84,Tuesday
3,4,C,São Paulo,Feminino,Arroz,8.52,3,Pix,2024-11-23,19:13,3,25.56,Saturday
4,5,A,São Paulo,Masculino,Açúcar,74.63,8,Cartão,2024-10-30,13:21,5,597.04,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,B,São Paulo,Masculino,Carne,71.15,1,Dinheiro,2024-11-29,12:09,2,71.15,Friday
296,297,B,Belo Horizonte,Masculino,Carne,92.67,8,Dinheiro,2024-01-20,21:48,3,741.36,Saturday
297,298,B,São Paulo,Masculino,Feijão,19.70,3,Dinheiro,2024-05-25,17:04,3,59.10,Saturday
298,299,B,Belo Horizonte,Masculino,Pão,57.66,6,Dinheiro,2024-11-11,22:42,1,345.96,Monday
299,300,B,São Paulo,Feminino,Leite,91.72,9,Cartão,2024-06-08,11:46,3,825.48,Saturday

In [6]:
#top 3 dias da semana com mais faturamento
dia_faturamento =df.groupby(['DiaSemana'])['Faturamento'].sum().sort_values(ascending=False)
dia_faturamento.head(3)

DiaSemana
Thursday    14726.37
Friday      11864.84
Saturday    11276.81
Name: Faturamento, dtype: float64

In [7]:
df['Hora'] = pd.to_datetime(df['Hora'], format="%H:%M").dt.hour.astype(int)

# Cria nova coluna "Periodo"
def definir_periodo(hora):
    if 5 <= hora < 12:
        return 'Manhã'
    elif 12 <= hora < 18:
        return 'Tarde'
    elif 18 <= hora < 24:
        return 'Noite'
    else:
        return 'Madrugada'

df['Periodo'] = df['Hora'].apply(definir_periodo)

df

,ID_Venda,Filial,Cidade,Genero,Produto,Preco_Unitario,Quantidade,Forma_Pagamento,Data,Hora,Avaliacao,Faturamento,DiaSemana,Periodo
0,1,C,Belo Horizonte,Feminino,Carne,73.63,5,Dinheiro,2024-01-03,13,2,368.15,Wednesday,Tarde
1,2,A,São Paulo,Masculino,Arroz,93.96,7,Cartão,2024-03-25,16,7,657.72,Monday,Tarde
2,3,C,São Paulo,Masculino,Pão,19.76,9,Pix,2024-10-08,19,3,177.84,Tuesday,Noite
3,4,C,São Paulo,Feminino,Arroz,8.52,3,Pix,2024-11-23,19,3,25.56,Saturday,Noite
4,5,A,São Paulo,Masculino,Açúcar,74.63,8,Cartão,2024-10-30,13,5,597.04,Wednesday,Tarde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,B,São Paulo,Masculino,Carne,71.15,1,Dinheiro,2024-11-29,12,2,71.15,Friday,Tarde
296,297,B,Belo Horizonte,Masculino,Carne,92.67,8,Dinheiro,2024-01-20,21,3,741.36,Saturday,Noite
297,298,B,São Paulo,Masculino,Feijão,19.70,3,Dinheiro,2024-05-25,17,3,59.10,Saturday,Tarde
298,299,B,Belo Horizonte,Masculino,Pão,57.66,6,Dinheiro,2024-11-11,22,1,345.96,Monday,Noite
299,300,B,São Paulo,Feminino,Leite,91.72,9,Cartão,2024-06-08,11,3,825.48,Saturday,Manhã

In [8]:
df.groupby(['Cidade'])['Faturamento'].sum().sort_values(ascending = False)

Cidade
São Paulo         31735.40
Belo Horizonte    21400.09
Rio de Janeiro    21007.52
Name: Faturamento, dtype: float64

In [9]:
faturamento_periodo = df.groupby(['Periodo'])['Faturamento'].sum().sort_values(ascending = False)
faturamento_periodo

Periodo
Noite    30583.01
Tarde    28466.34
Manhã    15093.66
Name: Faturamento, dtype: float64

In [10]:
df.groupby(['Filial'])['Faturamento'].sum().sort_values(ascending = False)

Filial
C    26636.20
A    24413.59
B    23093.22
Name: Faturamento, dtype: float64

In [20]:
df

def verifca_mes(Data):
  if Data.month == 1:
    return 'Janeiro'
  if Data.month == 2:
    return 'Fevereiro'
  if Data.month == 3:
    return 'Março'
  if Data.month == 4:
    return 'Abril'
  if Data.month == 5:
    return 'Maio'
  if Data.month == 6:
    return 'Junho'
  if Data.month == 7:
    return 'Julho'
  if Data.month == 8:
    return 'Agosto'
  if Data.month == 9:
    return 'Setembro'
  if Data.month == 10:
    return 'Outubro'
  if Data.month == 11:
    return 'Novembro'
  if Data.month == 12:
    return 'Dezembro'
df['Mes'] = df['Data'].apply(verifca_mes)
df

,ID_Venda,Filial,Cidade,Genero,Produto,Preco_Unitario,Quantidade,Forma_Pagamento,Data,Hora,Avaliacao,Faturamento,DiaSemana,Periodo,Mes
0,1,C,Belo Horizonte,Feminino,Carne,73.63,5,Dinheiro,2024-01-03,13,2,368.15,Wednesday,Tarde,Janeiro
1,2,A,São Paulo,Masculino,Arroz,93.96,7,Cartão,2024-03-25,16,7,657.72,Monday,Tarde,Março
2,3,C,São Paulo,Masculino,Pão,19.76,9,Pix,2024-10-08,19,3,177.84,Tuesday,Noite,Outubro
3,4,C,São Paulo,Feminino,Arroz,8.52,3,Pix,2024-11-23,19,3,25.56,Saturday,Noite,Novembro
4,5,A,São Paulo,Masculino,Açúcar,74.63,8,Cartão,2024-10-30,13,5,597.04,Wednesday,Tarde,Outubro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,B,São Paulo,Masculino,Carne,71.15,1,Dinheiro,2024-11-29,12,2,71.15,Friday,Tarde,Novembro
296,297,B,Belo Horizonte,Masculino,Carne,92.67,8,Dinheiro,2024-01-20,21,3,741.36,Saturday,Noite,Janeiro
297,298,B,São Paulo,Masculino,Feijão,19.70,3,Dinheiro,2024-05-25,17,3,59.10,Saturday,Tarde,Maio
298,299,B,Belo Horizonte,Masculino,Pão,57.66,6,Dinheiro,2024-11-11,22,1,345.96,Monday,Noite,Novembro
299,300,B,São Paulo,Feminino,Leite,91.72,9,Cartão,2024-06-08,11,3,825.48,Saturday,Manhã,Junho

In [23]:
filtro_mes = df.groupby(['Mes'])['Faturamento'].sum().sort_values(ascending = False)
filtro_mes

Mes
Maio         8180.98
Outubro      8039.55
Junho        7717.87
Março        7567.04
Setembro     7065.74
Fevereiro    6624.75
Abril        6446.17
Janeiro      5813.33
Dezembro     5341.68
Agosto       5013.74
Novembro     4793.63
Julho        1538.53
Name: Faturamento, dtype: float64